Bot:
    Name: buttbutt
    Login: buttbutt
    Realname: butt
    Password:
    Message-Delay: 10
    No-Verify: false
Channels:
    - '#afterlunch'
    - '##anotherchannel'
Server:
    Hostname: 'chat.freenode.net'
    Auto-Reconnect: true
SQL:
    Username: root
    Password:
    IP: 127.0.0.1
    Port:
    Database:
    Table-Prefix:

