Bot:
    Name: buttbutt
    Login: buttbutt
    Realname: butt
    Password:
    Message-Delay: 0
    No-Verify: false
Channels:
    - '#afterlunch'
    - '##anotherchannel'
Server:
    Hostname: 'chat.freenode.net'
    SSL: false
    Port: 6667
    Auto-Reconnect: true
SQL:
    Username: root
    Password: secret
    IP: 127.0.0.1
    Port: 3306
    Database: irc
    Table-Prefix: ircbutt

