Bot:
    Name: buttbutt
    Login: buttbutt
    Password:
    Message-Delay: 10
Channels:
    - '#oatpaste'
    - '##poopheads'
Server:
    Hostname: 'irc.esper.net'
    Auto-Reconnect: true
SQL:
    Username: poop
    Password:
    IP:
    Port:
    Database:
    Table-Prefix:

