Bot:
    Name: buttbutt
    Nickname: butt
    Login: buttbutt
    Realname: butt
    Password:
    Message-Delay: 0
    No-Verify: false
    Random-Response-Frequency: 100
API:
   CoinMarketCap: 'c08ee199-caf0-4efc-8399-9bcb90c8960a'
Channels:
    - '#afterlunch'
    - '##anotherchannel'
Server:
    Hostname: 'irc.libera.chat'
    SSL: false
    Port: 6667
    Auto-Reconnect: true
SQL:
    Username: root
    Password: secret
    IP: 127.0.0.1
    Port: 3306
    Database: irc
    Table-Prefix: ircbutt

