Bot:
    Name: buttbutt
    Login: buttbutt
    Realname: butt
    Password:
    Message-Delay: 10
    No-Verify: false
Channels:
    - '#gsbros'
    - '##anotherchannel'
Server:
    Hostname: 'chat.freenode.net'
    Auto-Reconnect: true
SQL:
    Username: poop
    Password:
    IP:
    Port:
    Database:
    Table-Prefix:

